hello = "Ciao!"
help = "Aiuto!"
cancel = "Annulla"
done = "Fatto"
welcome = "Benvenuto nel team!"
welcome_back = "Bentornato, felice di rivederti :)"

SR_IDNumber = "Numero di matricola"
faculty = "Corso di laurea"
name = "Nome"
surname = "Cognome"
lichess_nickname = "Nome utente lichess"
chess_nickname = "Nome utente chess"
fide_elo = "ELO Fide"